<a href="https://colab.research.google.com/github/Nirwa22/PyTorch_Youtube/blob/main/00_pytorch_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue Feb 27 08:47:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
#scalar
x = torch.tensor(7)

In [ ]:
x.type

<function Tensor.type>

In [ ]:
x.ndim#A scalar has no dimension

0

In [ ]:
x.item()

7

In [ ]:
y = torch.tensor([7,7])
y.ndim

1

In [ ]:
y.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[1,1],
                       [5,6]])
matrix

tensor([[1, 1],
        [5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
Matrix[1]

NameError: name 'Matrix' is not defined

In [ ]:
tensor = torch.tensor([[[2,4],[5,6],[7,8],[7,4]]])
tensor

tensor([[[2, 4],
         [5, 6],
         [7, 8],
         [7, 4]]])

In [ ]:
tensor.shape

torch.Size([1, 4, 2])

In [ ]:
tensor.ndim

3

In [ ]:
T = torch.tensor([[[[1,2,3],[1,2,1]]]])

In [ ]:
T.ndim

4

In [ ]:
#Create random tensor
k = torch.rand(224,224,3)
k.ndim,k.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
ones = torch.ones(size=(3,4))
zeros = torch.zeros(size=(3,4))
ones*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Creating a range of tensors
range = torch.arange(1,11,2)#(start,end,step)
range

tensor([1, 3, 5, 7, 9])

In [ ]:
#Creating tensors like
torch.ones_like(range,dtype = torch.float32)

tensor([1., 1., 1., 1., 1.])

In [ ]:
#Datatypes
r = torch.tensor([[3,5],[6,8]], dtype=torch.float32,device=None,requires_grad=False)
r.dtype

torch.float32

In [ ]:
h = r.type(torch.float16)
h

tensor([[3., 5.],
        [6., 8.]], dtype=torch.float16)

In [ ]:
h*float32_t

tensor([[ 9., 25.],
        [36., 64.]])

In [ ]:
import torch
k = torch.rand(1,2,dtype = torch.float32)
k

tensor([[0.9847, 0.5791]])

In [ ]:
k

tensor([0.6018, 0.7081, 0.6421])

In [ ]:
k.ndim

1

In [ ]:
x = torch.tensor(5)
x.item()


5

In [ ]:
t = torch.tensor([3,4])
t

tensor([3, 4])

In [ ]:
t.ndim

1

In [ ]:
t*k

tensor([[3.4465, 2.6640]])

In [ ]:
t.dtype,t.shape,t.device

(torch.int64, torch.Size([2]), device(type='cpu'))

***Tensor not in right shape,right device or right datatype**

In [ ]:
t.size() #t.size()=t.shape
#t.shape is an attribute while t.size() is a function

torch.Size([2])

**Manipulating tensors (tensors operations)**
1. Addition
2. Multiplication(elementwise)
3. Substraction
4. Division
5. Matrix Multiplication

In [ ]:
#Addition
r = torch.tensor([1,4,6])
k = torch.tensor([1,6,8])
l = torch.add(r,k) #Pytorch builtin function
r+k,l

(tensor([ 2, 10, 14]), tensor([ 2, 10, 14]))

In [ ]:
#Substraction
r = torch.tensor([1,4,6])
k = torch.tensor([1,6,8])
l = torch.sub(r,k) #Pytorch builtin function
r-k,l

(tensor([ 0, -2, -2]), tensor([ 0, -2, -2]))

In [ ]:
#Multiplication(element-wise)
l = torch.mul(r,k) #Pytorch builtin function
r*k,l

(tensor([ 1, 24, 48]), tensor([ 1, 24, 48]))

In [ ]:
#Division
l = torch.div(r,k)
r/k,l

(tensor([1.0000, 0.6667, 0.7500]), tensor([1.0000, 0.6667, 0.7500]))

**Matrix Multiplication**


1.   Element-wise Multiplication(with scalar)
2.   Matrix multiplication(very common in NN) or Dot product(both these are used interchangingly)



In [ ]:
torch.matmul(r,k)

tensor(73)

In [ ]:
import torch
q = torch.tensor([[1],[1],[0]])
t = torch.tensor([2,3,4])
torch.mul(q,t) #q*t

tensor([[2, 3, 4],
        [2, 3, 4],
        [0, 0, 0]])

In [ ]:
q = torch.tensor([1,1,0])
t = torch.tensor([2,3,4])

In [ ]:
%%time
torch.matmul(t,t) #Basically Dot product '@' could also be used

CPU times: user 62 µs, sys: 10 µs, total: 72 µs
Wall time: 75.3 µs


tensor(29)

In [ ]:
t@t

tensor(29)

In [ ]:
%%time
v = 0
for i in range(len(t)):
  v += t[i]*t[i]
print(v)

tensor(29)
CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.44 ms


**One of the most common errors in deep learning is shape errors**

Two main rules:

1.   The **inners dimension** should match
2.   The resulting matrix has the shape of the **outer dimension**



In [ ]:
import torch
k = torch.matmul(torch.rand(2,3), torch.rand(3,2)) #could use torch.mm too
#torch.matmul(torch.rand(2,3), torch.rand(2,3)) won't work because inner dimensions are not matching

Lets suppose there is a shape error but u can't fix it then use **transpose**

In [ ]:
tensor = torch.tensor([[2,3],[1,7],[5,6]])
tensor.T #Transpose

tensor([[2, 1, 5],
        [3, 7, 6]])

In [ ]:
tensor.T.shape , tensor.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
print(f"Shape of the tensor transpose : {tensor.T.shape}")

Shape of the tensor transpose : torch.Size([2, 3])


**Finding the min,max,mean,sum,etc(tensor aggregation)**

In [ ]:
torch.min(tensor) , torch.max(tensor)  #Max and Min

(tensor(1), tensor(7))

In [ ]:
tensor.max() , tensor.min() #Max and Min

(tensor(7), tensor(1))

In [ ]:
k = tensor.type(torch.float32)
k

tensor([[2., 3.],
        [1., 7.],
        [5., 6.]])

In [ ]:
k.mean() #Mean of the tensor

tensor(4.)

In [ ]:
# For mean the dtype needs to be float32
torch.mean(k)

tensor(4.)

In [ ]:
# Sum
torch.sum(k) , k.sum()

(tensor(24.), tensor(24.))

In [ ]:
torch.argmin(k) , torch.argmax(k) # Tells the position

(tensor(2), tensor(3))

##Reshaping, viewing and stacking tensors

*Reshaping - reshapes an input tensor to a defined shape.

*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking - combine multiple tensors(vstack and hstack)

*Squeeze and unsequeeze - removes all '1' dimensions ,add a '1' dimension respectively

*Permute - Return a view of an input with dimensions permuted (swapped) in a certain way.

In [ ]:
import torch
#Manipulating tensors
x = torch.arange(1.,10.,1)
x,x.shape,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9) #can't be (1,7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
#Change the view
#Similar to reshape
k = x.view(3,3)
x.shape , k.shape

(torch.Size([9]), torch.Size([3, 3]))

In [ ]:
k[:,1]=1
k, x #Making changes in k changes x too(k shares the same memory as the original tensor/x)

(tensor([[1., 1., 3.],
         [4., 1., 6.],
         [7., 1., 9.]]),
 tensor([1., 1., 3., 4., 1., 6., 7., 1., 9.]))

In [ ]:
#Stacking on top(vstack)
a = torch.arange(1,9)
b = torch.arange(1,9)
k = torch.stack([a,b],dim=0) # Or torch.vstack([a,b])
j = torch.stack([a,b],dim=1)
k , j , k.shape , j.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8],
         [1, 2, 3, 4, 5, 6, 7, 8]]),
 tensor([[1, 1],
         [2, 2],
         [3, 3],
         [4, 4],
         [5, 5],
         [6, 6],
         [7, 7],
         [8, 8]]),
 torch.Size([2, 8]),
 torch.Size([8, 2]))

In [ ]:
torch.hstack([a,b]).shape

torch.Size([16])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped

tensor([[1., 1., 3., 4., 1., 6., 7., 1., 9.]])

In [ ]:
torch.squeeze(x_reshaped)# One square bracket removed due to removal of a dimension(removes 1 size dimensions)

tensor([1., 1., 3., 4., 1., 6., 7., 1., 9.])

In [ ]:
#Squeeze unsequeeze
x_reshaped.shape, torch.squeeze(x_reshaped).shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
r = torch.unsqueeze(x_reshaped,dim=0)
r1 = torch.unsqueeze(x_reshaped,dim=1)
r2 = torch.unsqueeze(x_reshaped,dim=2)
r.shape,r1.shape,r2.shape

(torch.Size([1, 1, 9]), torch.Size([1, 1, 9]), torch.Size([1, 9, 1]))

In [ ]:
r1,x_reshaped

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
# torch.permute - returns a view of the original tensor with its dimension permuted
torch.permute(r1,(2,0,1)).shape , r1.shape

(torch.Size([9, 1, 1]), torch.Size([1, 1, 9]))

In [ ]:
print(f'Previous shape:{r1.shape}')
print(f'New shape:{torch.permute(r1,(2,0,1)).shape}')

Previous shape:torch.Size([1, 1, 9])
New shape:torch.Size([9, 1, 1])


In [ ]:
k = torch.permute(r1,(2,0,1))
r1[0,0,0]=89

In [ ]:
k[0,0,0]

tensor(89.)

In [ ]:
#Indexing
import torch
q = torch.arange(1,10).reshape(1,3,3)
q, q.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
q[0],   q[0][0],  q[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

**q[0]-targets the outermost bracket**

**q[0][0]-targets the first row**

**q[0][0][0]-targets the first element of the first row**

In [ ]:
q[0][2][1] #can't be q[1][2][1]

tensor(8)

**Actually q(0,3,3) so it has only one dimension at 0 position hence can't be q[1],only q[0]**

In [ ]:
q[1] #Gives error

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
# Also use"":" to select all of a target dimension
q[:,0] ,q[0]

(tensor([[1, 2, 3]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [ ]:
q[0],q

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [ ]:
q[:,2],q[:,1],q[:,0]

(tensor([[7, 8, 9]]), tensor([[4, 5, 6]]), tensor([[1, 2, 3]]))

In [ ]:
# Get all values of 0th and the 1st dimension but only index 1 of 2nd dimension
q[:,:,:] # Is equals to q (q=q[:,:,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
q[:,:,0],q[:,:,1],q[:,:,2]

(tensor([[1, 4, 7]]), tensor([[2, 5, 8]]), tensor([[3, 6, 9]]))

In [ ]:
q[:,1,0]

tensor([4])

In [ ]:
q[:,1,:]

tensor([[4, 5, 6]])

In [ ]:
q[0][1]

tensor([4, 5, 6])

**We use above to get any number from a tensor**

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
q[:,1,1] # Selecting middle tensor( ':' selects all the dimension)

tensor([5])

In [ ]:
q[0,1,1] # Selecting middle value

tensor(5)

In [ ]:
q[0,0,:] # result = tensor

tensor([1, 2, 3])

In [ ]:
#Exercise (value=9)
#Using index
q[0][2][2]

tensor(9)

In [ ]:
q[:,2,2]

tensor([9])

In [ ]:
#value = 3,6,9
q[:,:,2]

tensor([[3, 6, 9]])

##**PyTorch tensors and Numpy**

* NumPy is a popular scientific python
numerical computing library
* That is why pyTorch has functionality to interact with it.
* Data in NumPy,want in PyTorch tensor -> **torch.from_numpy(ndarray)**
* PyTorch tensor->NumPy-> **torch.Tensor.numpy()**

In [ ]:
#NumPy array to tensor
import numpy as np
array = np.arange(1.0,8.0)
T = torch.from_numpy(array)

In [ ]:
T ,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
T.dtype,array.dtype

(torch.float64, dtype('float64'))

In [ ]:
#Warning when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
k = T.type(torch.float32)
k.dtype

torch.float32

In [ ]:
k.dtype

torch.float32

In [ ]:
#Change the value of array
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
T # So changing the array did not change the value of the tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# Tensor to NumPy array
k.numpy()

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [ ]:
u = torch.ones(1,7)
o = u.numpy()
# From pytorch to numpy->default dtype of numpy = float64
# From numpy to pytorch->default dtype of pytorch = float32

In [ ]:
u

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# Changing tensor
u=u+1

In [ ]:
u,o

(tensor([[2., 2., 2., 2., 2., 2., 2.]]),
 array([[1., 1., 1., 1., 1., 1., 1.]], dtype=float32))

**Changing the tensor doesn't change the array**

# PyTorch reproducibility (taking random out of the random)
* Neural networks start with random numbers
* Apply tensor operation
* Update random numbers to try and manke them a better representation of the data
* Again and again and again....


In [ ]:
# Basically if we write torch.rand(3,3) it is going to generate a random set of values every single time.
torch.rand(3,3)

tensor([[0.8029, 0.1823, 0.7307],
        [0.5611, 0.2155, 0.6019],
        [0.3362, 0.3681, 0.7846]])

In [ ]:
torch.rand(3,3)

tensor([[0.8577, 0.6114, 0.3610],
        [0.6076, 0.5051, 0.6676],
        [0.9890, 0.6865, 0.3193]])

 *Hence to reduce the randomness in NN and pytorch comes the concept of* ***random seed***
 *Essentialy it "Flavour " the randomness*

In [ ]:
#Create two random tensors
A = torch.rand(3,4)
B = torch.rand(3,4)
print(A)
print(B)
print(A==B)#Comparison operator

tensor([[0.2117, 0.9601, 0.1853, 0.8123],
        [0.4533, 0.4340, 0.6703, 0.0572],
        [0.0127, 0.9428, 0.1887, 0.3096]])
tensor([[0.5825, 0.6583, 0.2929, 0.3693],
        [0.6865, 0.2942, 0.9013, 0.1626],
        [0.5435, 0.1510, 0.1531, 0.0608]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible random numbers
#Set the random seed
Random_seed = 42 #set to some numerical values(most common : 42,0,1234,77,100)
#FLAVORED RANDOMNESS WITH 42
torch.manual_seed(Random_seed)
E = torch.rand(3,4)
R = torch.rand(3,4)
print(E),print(R),
print(E==R)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#FIX THIS.HOW?
torch.manual_seed(Random_seed)
R = torch.rand(3,4)
R

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
print(R) , print(E==R)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(None, None)

**Torch.manual_seed generally works for one block of code**
* Use *torch.manual_seed* everytime you want to use random(rand) method

## Running tensors and pytorch objects on the GPUs(and making faster computations)

GPUs = faster computation on numbers,thanks to CUDA + NVIDIA hardware +PyTorch working behind the scenes to make e everything good.

### 1.Getting a GPU
1. Easiest-Google colab
2. Use your own GPU-takesalitle bit setup and requires the investment of purchasing a GPU
3. Use cloud computing- GCP,AWS,Azure,these services allow you to rent computers on the cloud and access them

In [ ]:
!nvidia-smi

Wed Mar  6 09:30:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch


In [ ]:
#Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
import torch
if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'

In [ ]:
device

'cuda'

In [ ]:
#Count number od devices
torch.cuda.device_count()

1

**For PyTorch since it is capable of running compute on the GPU or CPU,it's best practice to setup device agnostic code**
e.g.run on GPU if availai=able,else default to CPU

In [ ]:
#Setting up device agnostic code and putting tensors on and off the GPU
#Colab gives us free access to GPU

## 3. Putting tensors (and models on the GPU)

The reason we wamt our tensors/models on the GPU is because using GPU results in faster computation.
ML models define patterns and numbers,GPU are great for numerical calculations(Tensor operation)/faster computation or calculations

In [ ]:
#Create a tensor(default on the CPU)
y = torch.tensor([1,2,3])
y.device

device(type='cpu')

##Moving tensor to GPU

In [ ]:
# Move y(tensor) to GPU (if available)
y_on_GPU = y.to(device)#very commonly used
y_on_GPU.device

device(type='cuda', index=0)

**Numpy only works with CPU**



## Moving y from GPU back to CPU

In [ ]:
#Tensor on GPU,can't transfor to numpy
y_on_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**This the 3rd tensor issue discussed earlier (device issue)**

In [ ]:
#Set y_on_GPU to the CPU to resolve this problem
y_back_to_CPU = y_on_GPU.cpu()

In [ ]:
y_back_to_CPU .device


device(type='cpu')

In [ ]:
y_back_to_CPU.numpy()

array([1, 2, 3])

In [ ]:
y_on_GPU # Remains unchanged

tensor([1, 2, 3], device='cuda:0')

In [ ]:
## Exercises and Extra-curriculum

In [ ]:
#Random tensor with shape(7,7)
p = torch.rand(7,7)
p

tensor([[0.9244, 0.9395, 0.0331, 0.7749, 0.9918, 0.7117, 0.5862],
        [0.8158, 0.2985, 0.6766, 0.8550, 0.2370, 0.3536, 0.1543],
        [0.5445, 0.1857, 0.4622, 0.2112, 0.3035, 0.1118, 0.7675],
        [0.3101, 0.7704, 0.2481, 0.3619, 0.4777, 0.7369, 0.5791],
        [0.7796, 0.7383, 0.7626, 0.1030, 0.2443, 0.8684, 0.9015],
        [0.3848, 0.3125, 0.3572, 0.5773, 0.2717, 0.4290, 0.8132],
        [0.3142, 0.2015, 0.1345, 0.2549, 0.2869, 0.1551, 0.5963]])

In [ ]:
R = torch.rand(1,7).T

In [ ]:
U = torch.mul(p,R) # Or use p*R (7,7)
W = torch.matmul(p,R) # Or use p@R (7,1)
q = p*R
a = p@R

In [ ]:
U.shape,W.shape,q.shape,a.shape

(torch.Size([7, 7]),
 torch.Size([7, 1]),
 torch.Size([7, 7]),
 torch.Size([7, 1]))

In [ ]:
W

tensor([[2.5437],
        [1.4159],
        [1.2033],
        [2.0833],
        [2.4228],
        [1.5472],
        [0.9389]])

In [ ]:
random_seed = 0
torch.manual_seed(random_seed)
X = torch.rand(7,7)
torch.manual_seed(random_seed)
Y = torch.rand(1,7)

In [ ]:
X , Y

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [ ]:
torch.matmul(X,Y.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
##6
torch.manual_seed(1234)
w = torch.rand(2,3)
w_new = w.to(device)
torch.manual_seed(1234)
r = torch.rand(2,3)
r_new = r.to(device)
w,r,w_new,r_new

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [ ]:
#Checking for th access of GPU
device ='cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
print(f"Device : {device}")

Device : cuda


In [ ]:
torch.manual_seed(1234)
w = torch.rand(2,3)
w_new = w.to(device)
#torch.manual_seed(1234)
r = torch.rand(2,3)
r_new = r.to(device)
w_new,r_new

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
##7
q_1 = torch.matmul(w_new.T,r_new) #3x3
q_2 = torch.matmul(w_new,r_new.T) #2x2
q_1,q_2
print(f"q_1 Shape : {q_1}\n{q_1.shape}")
print(f"q_2 Shape : {q_2}\n{q_2.shape}")

q_1 Shape : tensor([[0.1230, 0.3009, 0.2260],
        [0.0401, 0.2338, 0.3036],
        [0.2457, 0.6707, 0.5696]], device='cuda:0')
torch.Size([3, 3])
q_2 Shape : tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


In [ ]:
#8
q_2.max() , q_2.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
#9
q_2.argmax(),q_2.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
#10
torch.manual_seed(7)
q = torch.rand(1,1,1,10)
y = torch.squeeze(q) #Squeeze removes single dimensions
q , q.shape ,y, y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

**The End**